// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCpq1lR0awCRNUKWV3x7caQaebPuss8p0',
    appId: '1:241814389011:web:d166d00485354bbc751ae6',
    messagingSenderId: '241814389011',
    projectId: 'fir-001-79553',
    authDomain: 'fir-001-79553.firebaseapp.com',
    storageBucket: 'fir-001-79553.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjmv-uFl6Cxfb_RG8L4LuXrW91IW3F9k8',
    appId: '1:241814389011:android:66ecf94c1381acc6751ae6',
    messagingSenderId: '241814389011',
    projectId: 'fir-001-79553',
    storageBucket: 'fir-001-79553.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm4E2kmRMYDIQMZBdfSQLUDpdFUYEbK7s',
    appId: '1:241814389011:ios:0a5ee760fb1b2832751ae6',
    messagingSenderId: '241814389011',
    projectId: 'fir-001-79553',
    storageBucket: 'fir-001-79553.appspot.com',
    iosBundleId: 'com.example.firebase01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm4E2kmRMYDIQMZBdfSQLUDpdFUYEbK7s',
    appId: '1:241814389011:ios:683244100e490681751ae6',
    messagingSenderId: '241814389011',
    projectId: 'fir-001-79553',
    storageBucket: 'fir-001-79553.appspot.com',
    iosBundleId: 'com.example.firebase01.RunnerTests',
  );
}
